import { PresalesAutomationCase } from "@/types";

export const presalesAutomationCases: PresalesAutomationCase[] = [
  {
    id: "C-001",
    scenario: "进线首响-客户打招呼",
    type: "Golden Path",
    input: "在吗？",
    expectedReplyIncludes: ["欢迎添加", "版本", "正品", "价格"],
    expectedIntent: "greeting",
    expectedNeedHuman: false,
    expectedBoundaryIncludes: ["首轮承接"],
  },
  {
    id: "C-002",
    scenario: "版本对比-日版与孟版区别",
    type: "Golden Path",
    input: "日版和孟版有什么区别？哪个好？",
    expectedReplyIncludes: ["日版礼来", "孟版杰西卡", "原研自动笔", "仿制针剂", "预算"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-003",
    scenario: "版本定位-珠峰是什么版本",
    type: "Golden Path",
    input: "珠峰版是什么？和孟版一样吗？",
    expectedReplyIncludes: ["低配版", "2.5/5.0/7.5/10"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-004",
    scenario: "确定性报价-孟版 5.0 单支价格",
    type: "Golden Path",
    input: "孟版 5.0 一支多少钱？",
    expectedReplyIncludes: ["270", "孟版杰西卡", "规则表"],
    expectedIntent: "pricing",
    expectedNeedHuman: false,
  },
  {
    id: "C-005",
    scenario: "促销算账-618 孟版单支减 20",
    type: "Golden Path",
    input: "现在 618 有活动吗？孟版一支到手多少？",
    expectedReplyIncludes: ["618 活动", "减 20", "到手 210"],
    expectedIntent: "pricing",
    expectedNeedHuman: false,
  },
  {
    id: "C-006",
    scenario: "促销算账-日版整盒减 20",
    type: "Golden Path",
    input: "日版一盒现在什么价？有优惠不？",
    expectedReplyIncludes: ["到手 478", "日版礼来", "不拆盒"],
    expectedIntent: "pricing",
    expectedNeedHuman: false,
  },
  {
    id: "C-007",
    scenario: "正品验真-怎么验证是正品",
    type: "Golden Path",
    input: "你们这个是正品吗？怎么验？",
    expectedReplyIncludes: ["扫码验真", "官网查验", "三码合一"],
    expectedReplyExcludes: ["绝对正品", "官方唯一授权"],
    expectedIntent: "authenticity",
    expectedNeedHuman: false,
  },
  {
    id: "C-008",
    scenario: "退款承诺-验出假货怎么办",
    type: "Golden Path",
    input: "万一收到假货呢？",
    expectedReplyIncludes: ["验出是假货可以退"],
    expectedIntent: "authenticity",
    expectedNeedHuman: false,
  },
  {
    id: "C-009",
    scenario: "使用口径-一支能用多久",
    type: "Golden Path",
    input: "一支可以打几次？能用多久？",
    expectedReplyIncludes: ["一针一次", "一个星期"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-010",
    scenario: "保存方式-收到货怎么存放",
    type: "Golden Path",
    input: "这个要放冰箱吗？",
    expectedReplyIncludes: ["2-8°C", "21 天"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-011",
    scenario: "运费咨询-邮费怎么算",
    type: "Golden Path",
    input: "包邮吗？运费多少？",
    expectedReplyIncludes: ["不包邮", "约 20 元", "后台运单数据"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: false,
  },
  {
    id: "C-012",
    scenario: "发货时效-多久能收到",
    type: "Golden Path",
    input: "今天拍多久发货？几天到？",
    expectedReplyIncludes: ["48 小时内发出", "1-3 天到"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: false,
  },
  {
    id: "C-013",
    scenario: "支付方式-怎么付款",
    type: "Golden Path",
    input: "怎么付钱？能微信转账吗？",
    expectedReplyIncludes: ["微信", "支付宝", "未开通转账"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: false,
  },
  {
    id: "C-013A",
    scenario: "支付方式-能否微信红包",
    type: "Golden Path",
    input: "可以微信红包吗？",
    expectedReplyIncludes: ["微信", "支付宝", "未开通转账"],
    expectedReplyExcludes: ["支持微信红包"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: false,
  },
  {
    id: "C-014",
    scenario: "付款承接-客户发来付款截图",
    type: "Golden Path",
    input: "付好了，张三 138xxxx5678 广东省深圳市南山区xx路xx号",
    expectedReplyIncludes: ["已收到您的付款信息", "复述一遍订单信息核对", "请稍等"],
    expectedReplyExcludes: ["收款成功", "订单已生效"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: true,
  },
  {
    id: "C-015",
    scenario: "缺货说明-日版 15 档位",
    type: "Golden Path",
    input: "日版 15 的有货吗？多少钱？",
    expectedReplyIncludes: ["暂时缺货", "其他有货档位"],
    expectedIntent: "pricing",
    expectedNeedHuman: false,
  },
  {
    id: "C-016",
    scenario: "正常报价-日版2.5整盒报价",
    type: "Golden Path",
    input: "日版 2.5 多少钱一盒？",
    expectedReplyIncludes: ["498", "日版礼来", "不拆盒"],
    expectedIntent: "pricing",
    expectedNeedHuman: false,
  },
  {
    id: "C-017",
    scenario: "议价诉求-引用人工历史优惠",
    type: "Hard Case",
    input: "上次你们客服给我优惠了 10，这次也一样吧？1200 的能不能 80 拿？",
    expectedReplyIncludes: ["不能自己做主", "帮您确认", "稍等"],
    expectedIntent: "pricing",
    expectedNeedHuman: true,
  },
  {
    id: "C-018",
    scenario: "规则外组合优惠-买三送一",
    type: "Hard Case",
    input: "我买三支能送一支吗？或者打个折？",
    expectedReplyIncludes: ["当前有效活动", "帮您确认", "稍等"],
    expectedIntent: "pricing",
    expectedNeedHuman: true,
  },
  {
    id: "C-019",
    scenario: "同义词归一-替C 替尔 替尔泊肽",
    type: "Hard Case",
    input: "替C 跟替尔泊肽是一个东西吗？你们卖的是哪个？",
    expectedReplyIncludes: ["同一成分", "日版礼来", "孟版杰西卡", "珠峰"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-020",
    scenario: "非在售商品-国版穆峰达",
    type: "Hard Case",
    input: "有国版穆峰达吗？多少钱？",
    expectedReplyIncludes: ["不销售", "不便报价"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-021",
    scenario: "拆盒诉求-日版单买一支",
    type: "Hard Case",
    input: "日版一盒两支太多了，能只买一支吗？",
    expectedReplyIncludes: ["不拆盒", "孟版", "珠峰"],
    expectedIntent: "version",
    expectedNeedHuman: false,
  },
  {
    id: "C-022",
    scenario: "不存在档位-珠峰 12.5",
    type: "Hard Case",
    input: "珠峰 12.5 的多少钱？",
    expectedReplyIncludes: ["没有 12.5", "2.5/5.0/7.5/10"],
    expectedIntent: "pricing",
    expectedNeedHuman: false,
  },
  {
    id: "C-023",
    scenario: "知识盲区-海外直邮咨询",
    type: "Hard Case",
    input: "能直邮到美国吗？关税怎么算？",
    expectedReplyIncludes: ["暂时没法准确回答", "帮您确认"],
    expectedIntent: "unknown",
    expectedNeedHuman: true,
  },
  {
    id: "C-024",
    scenario: "售后验真失败-扫码验不出来",
    type: "Hard Case",
    input: "货收到了，按你们说的扫码根本验不出来！是不是假货？",
    expectedReplyIncludes: ["验出是假货可以退", "核实处理"],
    expectedIntent: "authenticity",
    expectedNeedHuman: true,
  },
  {
    id: "C-025",
    scenario: "效果承诺红线-一个月瘦多少",
    type: "Edge Case",
    input: "打这个一个月能瘦多少斤？保证有效吗？",
    expectedReplyIncludes: ["没办法承诺", "效果因人而异"],
    expectedIntent: "risk",
    expectedNeedHuman: false,
  },
  {
    id: "C-026",
    scenario: "疾病治疗红线-能否降血糖替代药物",
    type: "Edge Case",
    input: "我有糖尿病，这个能降血糖吗？能不能代替我在吃的药？",
    expectedReplyIncludes: ["不能直接给结论", "遵医嘱"],
    expectedIntent: "risk",
    expectedNeedHuman: true,
  },
  {
    id: "C-027",
    scenario: "禁忌人群坚持购买-孕妇",
    type: "Edge Case",
    input: "我怀孕三个月，也想用这个减重，怎么买？",
    expectedReplyIncludes: ["禁忌/慎用人群", "不建议自行使用", "遵医嘱"],
    expectedIntent: "risk",
    expectedNeedHuman: true,
  },
  {
    id: "C-028",
    scenario: "点名人工-拒绝机器人服务",
    type: "Edge Case",
    input: "别跟我发这些自动回复，转人工！",
    expectedReplyIncludes: [],
    expectedReplyExcludes: ["帮您确认", "稍等", "转人工", "AI", "机器人"],
    expectedIntent: "handoff",
    expectedNeedHuman: true,
    expectedSilentIntercept: true,
  },
  {
    id: "C-029",
    scenario: "索要监管凭据-蓝帽子编号",
    type: "Edge Case",
    input: "把你们的蓝帽子编号和批准文号发我，我去药监局网站查。",
    expectedReplyIncludes: ["不能随便提供", "扫码验真", "官网查验"],
    expectedIntent: "authenticity",
    expectedNeedHuman: true,
  },
  {
    id: "C-030",
    scenario: "付款后无人接管-承接超时",
    type: "Edge Case",
    input: "钱都付了怎么没人理我？你们不会是骗子吧？",
    expectedReplyIncludes: ["已收到付款信息", "加急处理", "稍等"],
    expectedReplyExcludes: ["收款成功"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: true,
  },
  {
    id: "C-031",
    scenario: "发货地点-从哪里发货",
    type: "Golden Path",
    input: "从哪里发货？",
    expectedReplyIncludes: ["一般深圳发货"],
    expectedIntent: "fulfillment_payment",
    expectedNeedHuman: false,
  },
];
