import { PresalesKnowledgeBase } from "@/types";

export const quickQuestions = [
  { label: "在吗？", text: "在吗？" },
  { label: "日版孟版区别", text: "日版和孟版有什么区别？哪个好？" },
  { label: "孟版 5.0 价格", text: "孟版 5.0 一支多少钱？" },
  { label: "618 活动", text: "现在 618 有活动吗？孟版一支到手多少？" },
  { label: "正品验真", text: "你们这个是正品吗？怎么验？" },
  { label: "风险咨询", text: "这个有风险吗？" },
  { label: "保存方式", text: "这个要放冰箱吗？" },
  { label: "付款承接", text: "付好了，张三 138xxxx5678 广东省深圳市南山区xx路xx号" },
];

export const presalesKnowledgeBase: PresalesKnowledgeBase = {
  meta: {
    title: "私域电商售前客服 · 售前问答知识库",
    productName: "企微 AI 售前助手（RAG 1v1 自动回复）",
    generatedBy: "presales-qa-agent",
  },
  welcomeTemplate:
    "哈喽～欢迎添加，专注替西帕肽正品渠道，规格齐全、价优靠谱，支持一对一用量指导，有需要随时滴滴我～",
  identityReply:
    "我是您的专属客服，专注替西帕肽正品渠道，规格齐全、价优靠谱，有什么可以帮您的吗？",
  synonymsNote:
    "替C = 替尔 = 替尔泊肽（替西帕肽 Tirzepatide）是同一成分的不同叫法；本店在售日版礼来、孟版杰西卡、珠峰三个版本。",
  routing: {
    confidenceThreshold: 0.34,
    intentKeywords: {
      identity: ["你是谁", "你叫什么", "叫什么名字", "机器人", "你是AI", "你是真人", "你是人工", "你是客服", "你是什么"],
      handoff: ["转人工", "人工", "真人", "投诉", "不放心", "骗子"],
      risk: [
        "瘦多少",
        "瘦几斤",
        "多久见效",
        "保证",
        "效果",
        "有没有用",
        "治疗",
        "治病",
        "降血糖",
        "血糖",
        "代替药",
        "替代药",
        "副作用",
        "恶心",
        "孕妇",
        "备孕",
        "怀孕",
        "哺乳",
        "甲状腺",
        "甲减",
        "胰岛素",
        "磺脲",
        "过敏",
        "肾功能",
        "禁忌",
      ],
      fulfillment_payment: [
        "付款",
        "支付",
        "怎么付",
        "付钱",
        "转账",
        "微信",
        "支付宝",
        "红包",
        "发货",
        "从哪发",
        "多久到",
        "几天到",
        "快递",
        "物流",
        "运费",
        "包邮",
        "邮费",
        "付好了",
        "截图",
        "下单",
        "地址",
      ],
      pricing: [
        "多少钱",
        "价格",
        "什么价",
        "报价",
        "优惠",
        "活动",
        "到手",
        "便宜",
        "折扣",
        "打折",
        "减",
        "送",
        "一支多少",
        "一盒多少",
        "几支",
        "几盒",
        "618",
      ],
      authenticity: [
        "正品",
        "真的假的",
        "真假",
        "验真",
        "验",
        "扫码",
        "假货",
        "退款",
        "退货",
        "蓝帽子",
        "批准文号",
        "注册证",
      ],
      version: [
        "版本",
        "日版",
        "孟版",
        "珠峰",
        "区别",
        "哪个好",
        "成分",
        "替尔",
        "替C",
        "替西帕肽",
        "泊肽",
        "原研",
        "仿制",
        "自动笔",
        "针剂",
        "整盒",
        "只买一支",
        "太多",
        "穆峰达",
        "国版",
        "打几次",
        "用多久",
        "几次",
        "怎么用",
        "放冰箱",
        "冰箱",
        "冷藏",
        "保存",
        "存放",
        "冷冻",
      ],
    },
  },
  productVersions: [
    {
      id: "v_ri",
      name: "日版礼来",
      aliases: ["日版", "礼来"],
      packageDesc: "一盒两支",
      productForm: "原研自动笔",
      usageDesc: "一针一次，管一个星期",
      storageDesc: "未开封 2-8°C 冷藏、禁止冷冻；已开封 <30°C 常温可存 21 天",
      compareNote: "原研自动笔，操作便捷，价格带较高",
      integralOnly: true,
      doses: ["2.5", "5.0", "7.5", "10", "12.5", "15"],
    },
    {
      id: "v_meng",
      name: "孟版杰西卡",
      aliases: ["孟版", "杰西卡"],
      packageDesc: "一盒一支",
      productForm: "仿制针剂",
      usageDesc: "一针一次，管一个星期",
      storageDesc: "未开封 2-8°C 冷藏、禁止冷冻；已开封 <30°C 常温可存 21 天",
      compareNote: "仿制针剂，性价比较高",
      integralOnly: false,
      doses: ["2.5", "5.0", "7.5", "10", "12.5", "15"],
    },
    {
      id: "v_zhu",
      name: "珠峰",
      aliases: ["珠峰"],
      packageDesc: "一盒一支",
      productForm: "仿制针剂",
      usageDesc: "一针一次，管一个星期",
      storageDesc: "未开封 2-8°C 冷藏、禁止冷冻；已开封 <30°C 常温可存 21 天",
      compareNote: "珠峰是孟版杰西卡的低配版，入门价格带",
      integralOnly: false,
      doses: ["2.5", "5.0", "7.5", "10"],
    },
  ],
  skuPrices: [
    { version: "孟版杰西卡", dose: "2.5", listPrice: 230, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "孟版杰西卡", dose: "5.0", listPrice: 270, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "孟版杰西卡", dose: "7.5", listPrice: 300, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "孟版杰西卡", dose: "10", listPrice: 340, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "孟版杰西卡", dose: "12.5", listPrice: 370, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "孟版杰西卡", dose: "15", listPrice: 400, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "日版礼来", dose: "2.5", listPrice: 498, sessionPrice: null, conflict: false, stock: "in_stock", unit: "盒" },
    { version: "日版礼来", dose: "5.0", listPrice: 698, sessionPrice: null, conflict: false, stock: "in_stock", unit: "盒" },
    { version: "日版礼来", dose: "7.5", listPrice: 998, sessionPrice: null, conflict: false, stock: "in_stock", unit: "盒" },
    { version: "日版礼来", dose: "10", listPrice: 1190, sessionPrice: null, conflict: false, stock: "in_stock", unit: "盒" },
    { version: "日版礼来", dose: "12.5", listPrice: 1590, sessionPrice: null, conflict: false, stock: "in_stock", unit: "盒" },
    { version: "日版礼来", dose: "15", listPrice: null, sessionPrice: null, conflict: false, stock: "out_of_stock", unit: "盒" },
    { version: "珠峰", dose: "2.5", listPrice: 240, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "珠峰", dose: "5.0", listPrice: 300, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "珠峰", dose: "7.5", listPrice: 330, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
    { version: "珠峰", dose: "10", listPrice: 360, sessionPrice: null, conflict: false, stock: "in_stock", unit: "支" },
  ],
  promoRules: [
    { id: "PROMO-001", name: "618 活动·孟版单支", version: "孟版杰西卡", scope: "per_unit", discount: 20, validity: "active" },
    { id: "PROMO-002", name: "618 活动·日版整盒", version: "日版礼来", scope: "per_order", discount: 20, validity: "active" },
  ],
  manualOnlyPromos: ["优惠 10（人工口径，未统一）", "1200-80=1120（孟版 7.5×4，人工组合口径）"],
  authenticityProofs: {
    verifySteps: ["扫码验真", "官网查验（三码合一，保真保活）"],
    packaging: ["原厂包装 + 防伪标"],
    refundPromise: "到货后验出是假货可以退",
    forbidden: ["批准文号 / 注册证书编号 / 质检结论 / 蓝帽子编号", "绝对正品 / 官方唯一授权 / 国家级 等绝对化表述"],
  },
  complianceWhitelist: [
    {
      intent: "效果承诺",
      triggerWords: ["瘦多少", "瘦几斤", "多久见效", "保证", "有没有用", "效果"],
      responseMode: "safe_reply",
      reply: "每个人的情况不一样，没办法承诺具体能瘦多少或多久见效，效果因人而异，具体以产品说明和个人使用情况为准哦。",
    },
    {
      intent: "疾病治疗",
      triggerWords: ["治疗", "治病", "降血糖", "血糖", "代替药", "替代药", "治好"],
      responseMode: "transfer",
      reply: "这类和疾病、用药相关的问题我不能直接给结论，建议遵医嘱。我帮您确认一下，稍等哦～",
    },
    {
      intent: "副作用与禁忌",
      triggerWords: ["副作用", "恶心", "嗜睡", "口渴", "便秘", "呕吐"],
      responseMode: "safe_reply",
      reply: "常见反应包括饱腹感、恶心、嗜睡、口渴、便秘、呕吐，部分人会发热；如有明显不适请停用并咨询医生。具体情况我帮您确认一下，稍等哦～",
    },
  ],
  contraindications: {
    groups: ["孕妇", "备孕", "怀孕", "哺乳", "甲状腺", "甲减", "甲状腺结节", "胰岛素", "磺脲", "过敏", "肾功能"],
    reply:
      "您提到的情况属于禁忌/慎用人群（如甲状腺病史、正在用胰岛素/磺脲类、备孕孕产期等），这种情况不建议自行使用，需遵医嘱。我帮您确认一下具体情况，稍等哦～",
  },
  fulfillmentPayment: {
    paymentMethods: ["微信", "支付宝"],
    paymentUnavailable: "企微未开通转账收款功能",
    shippingOrigin: "一般深圳",
    shipTime: "出单号后 48 小时内发出",
    deliveryTime: "顺丰冷链，揽收后 1-3 天到",
    freight: "不包邮，顺丰冷链到付约 20 元（非固定，以后台运单数据为准；泡沫箱 + 保温袋 + 冰袋）",
    screenshotHandoff: "已收到您的付款信息啦～稍后我们会跟您复述一遍订单信息核对，确认无误后安排发货，请稍等。",
  },
  usageStorage: {
    usage: "一针一次，管一个星期，每周使用一次；新手建议先从 2.5 起",
    storageUnopened: "未开封 2-8°C 冷藏，禁止冷冻",
    storageOpened: "已开封 <30°C 常温可存 21 天；无冰箱时可用泡沫冰袋冷藏箱",
    sideEffects: "饱腹感、恶心、嗜睡、口渴、便秘、呕吐，部分人发热",
  },
  notInScope: [
    {
      item: "国版穆峰达",
      aliases: ["穆峰达", "国版"],
      reply: "国版穆峰达需要去医院开，本店不销售、也不便报价，可以帮您介绍在售的日版礼来 / 孟版杰西卡 / 珠峰。",
    },
  ],
};
